apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: 135188036963.dkr.ecr.ap-south-1.amazonaws.com/capstone-app
    newName: 135188036963.dkr.ecr.ap-south-1.amazonaws.com/capstone-app
    newTag: d2d8fad1dbda0fddf94a551adbe071499c8faf6c
