apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: 163265929593.dkr.ecr.ap-south-1.amazonaws.com/capstone-app
    newName: 163265929593.dkr.ecr.ap-south-1.amazonaws.com/capstone-app
    newTag: PLACEHOLDER