apiVersion: apps/v1

kind: Deployment

metadata:
  name: capstone-app

  labels:
    app: capstone-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: capstone-app

  template:
    metadata:
      labels:
        app: capstone-app

    spec:
      serviceAccountName: capstone-app

      initContainers:
        - name: database-init

          image: 135188036963.dkr.ecr.ap-south-1.amazonaws.com/capstone-app:PLACEHOLDER

          command:
            - python
            - init_db.py

          env:
            - name: AWS_REGION
              value: "ap-south-1"

            - name: DB_SECRET_NAME
              value: "capstone/database"

            - name: DB_HOST
              value: "capstone-db.cr4kuc4cwmyd.ap-south-1.rds.amazonaws.com"

            - name: DB_NAME
              value: "appdb"

      containers:
        - name: capstone-app

          image: 135188036963.dkr.ecr.ap-south-1.amazonaws.com/capstone-app:PLACEHOLDER

          ports:
            - containerPort: 5000

          env:
            - name: AWS_REGION
              value: "ap-south-1"

            - name: DB_SECRET_NAME
              value: "capstone/database"

            - name: DB_HOST
              value: "capstone-db.cr4kuc4cwmyd.ap-south-1.rds.amazonaws.com"

            - name: DB_NAME
              value: "appdb"

            - name: S3_BUCKET
              value: "capstone-135188036963-app"

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /health
              port: 5000

            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 5000

            initialDelaySeconds: 30
            periodSeconds: 20