apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass

metadata:
  name: capstone-database
  namespace: default

spec:
  provider: aws

  parameters:
    region: ap-south-1
    usePodIdentity: "true"

    objects: |
      - objectName: "capstone/database"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: DB_USER
          - path: password
            objectAlias: DB_PASSWORD

      - objectName: "/capstone/database/host"
        objectType: "ssmparameter"
        objectAlias: DB_HOST

      - objectName: "/capstone/database/name"
        objectType: "ssmparameter"
        objectAlias: DB_NAME

  secretObjects:
    - secretName: database-secret
      type: Opaque

      data:
        - objectName: DB_USER
          key: DB_USER

        - objectName: DB_PASSWORD
          key: DB_PASSWORD

        - objectName: DB_HOST
          key: DB_HOST

        - objectName: DB_NAME
          key: DB_NAME
