apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: 135188036963.dkr.ecr.ap-south-1.amazonaws.com/capstone-app
    newName: 135188036963.dkr.ecr.ap-south-1.amazonaws.com/capstone-app
    newTag: 1147aee055bd1e0bc6e5b328f43e392dd4bdc640
