apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: 135188036963.dkr.ecr.ap-south-1.amazonaws.com/capstone-app
    newName: 135188036963.dkr.ecr.ap-south-1.amazonaws.com/capstone-app
    newTag: 426efe2d7f2459e84aaa51afc1cbd9cfccea44e7
