apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: 135188036963.dkr.ecr.ap-south-1.amazonaws.com/capstone-app
    newName: 135188036963.dkr.ecr.ap-south-1.amazonaws.com/capstone-app
    newTag: 74887ea2d42a6e915209bf8170c1f974c59ce4b9
